### ISSUE TITLE
todo: react

### ISSUE THREAD

**Issue by kimkmin357** [kimkmin357/dev-web#1]
- [x] 개발환경 구성
- [x] 생활코딩 React 강좌 수강
- [x] 튜토리얼 문서 학습
- [x] nodejs express와 react app 연동

**Comment by kimkmin357** [comment]
생활코딩 React 강좌 링크 입니다.  https://youtube.com/playlist?list=PLuHgQVnccGMCRv6f8H9K5Xwsdyg4sFSdi
@dev-heaseok @DeukHan

**Comment by dev-heeseok** [comment]
@kimkmin357 
Assign, Labels, Project, Milestone 추가 및 tutorial branch 를 생성하면 더 좋을 것 같습니다.

**Comment by kimkmin357** [comment]
토이프로젝트는 여기 todo 항목에서는 제거
